name: Windows CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  validate:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # Copied from here:
      # <https://docs.travis-ci.com/user/languages/rust/#default-build-script>
      #
      # FIXME: Replace "build" with "test" once it passes.
      - run: cargo build --workspace
